/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EnderecoDto,
} from '../models/index';
import {
    EnderecoDtoFromJSON,
    EnderecoDtoToJSON,
} from '../models/index';

export interface ApiAddressCepGetRequest {
    cep: string;
}

/**
 * 
 */
export class AddressApi extends runtime.BaseAPI {

    /**
     */
    async apiAddressCepGetRaw(requestParameters: ApiAddressCepGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnderecoDto>> {
        if (requestParameters['cep'] == null) {
            throw new runtime.RequiredError(
                'cep',
                'Required parameter "cep" was null or undefined when calling apiAddressCepGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Address/{cep}`;
        urlPath = urlPath.replace(`{${"cep"}}`, encodeURIComponent(String(requestParameters['cep'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnderecoDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiAddressCepGet(requestParameters: ApiAddressCepGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnderecoDto> {
        const response = await this.apiAddressCepGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
