/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EnderecoDto,
  GetCepInput,
} from '../models/index';
import {
    EnderecoDtoFromJSON,
    EnderecoDtoToJSON,
    GetCepInputFromJSON,
    GetCepInputToJSON,
} from '../models/index';

export interface ApiAddressPostRequest {
    getCepInput?: GetCepInput;
}

/**
 * 
 */
export class AddressApi extends runtime.BaseAPI {

    /**
     */
    async apiAddressPostRaw(requestParameters: ApiAddressPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EnderecoDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Address`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetCepInputToJSON(requestParameters['getCepInput']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EnderecoDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiAddressPost(requestParameters: ApiAddressPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EnderecoDto> {
        const response = await this.apiAddressPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
