/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommonAreaDto,
  CommonAreaPhotoDto,
  UploadCommonAreaPhotoInput,
  UpsertCommonAreaInput,
} from '../models/index';
import {
    CommonAreaDtoFromJSON,
    CommonAreaDtoToJSON,
    CommonAreaPhotoDtoFromJSON,
    CommonAreaPhotoDtoToJSON,
    UploadCommonAreaPhotoInputFromJSON,
    UploadCommonAreaPhotoInputToJSON,
    UpsertCommonAreaInputFromJSON,
    UpsertCommonAreaInputToJSON,
} from '../models/index';

export interface ApiCommonAreaAreasAreaIdPhotosGetRequest {
    areaId: number;
    includeData?: boolean;
}

export interface ApiCommonAreaCondominiumCondominiumIdGetRequest {
    condominiumId: number;
}

export interface ApiCommonAreaIdGetRequest {
    id: number;
}

export interface ApiCommonAreaPhotosPhotoIdDeleteRequest {
    photoId: number;
}

export interface ApiCommonAreaPhotosPhotoIdGetRequest {
    photoId: number;
    includeData?: boolean;
}

export interface ApiCommonAreaPhotosPhotoIdRawGetRequest {
    photoId: number;
}

export interface ApiCommonAreaPhotosUploadPostRequest {
    uploadCommonAreaPhotoInput?: UploadCommonAreaPhotoInput;
}

export interface ApiCommonAreaUpsertPostRequest {
    upsertCommonAreaInput?: UpsertCommonAreaInput;
}

/**
 * 
 */
export class CommonAreaApi extends runtime.BaseAPI {

    /**
     */
    async apiCommonAreaAreasAreaIdPhotosGetRaw(requestParameters: ApiCommonAreaAreasAreaIdPhotosGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommonAreaPhotoDto>>> {
        if (requestParameters['areaId'] == null) {
            throw new runtime.RequiredError(
                'areaId',
                'Required parameter "areaId" was null or undefined when calling apiCommonAreaAreasAreaIdPhotosGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeData'] != null) {
            queryParameters['includeData'] = requestParameters['includeData'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea/Areas/{areaId}/Photos`;
        urlPath = urlPath.replace(`{${"areaId"}}`, encodeURIComponent(String(requestParameters['areaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommonAreaPhotoDtoFromJSON));
    }

    /**
     */
    async apiCommonAreaAreasAreaIdPhotosGet(requestParameters: ApiCommonAreaAreasAreaIdPhotosGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommonAreaPhotoDto>> {
        const response = await this.apiCommonAreaAreasAreaIdPhotosGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCommonAreaCondominiumCondominiumIdGetRaw(requestParameters: ApiCommonAreaCondominiumCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommonAreaDto>>> {
        if (requestParameters['condominiumId'] == null) {
            throw new runtime.RequiredError(
                'condominiumId',
                'Required parameter "condominiumId" was null or undefined when calling apiCommonAreaCondominiumCondominiumIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea/Condominium/{condominiumId}`;
        urlPath = urlPath.replace(`{${"condominiumId"}}`, encodeURIComponent(String(requestParameters['condominiumId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommonAreaDtoFromJSON));
    }

    /**
     */
    async apiCommonAreaCondominiumCondominiumIdGet(requestParameters: ApiCommonAreaCondominiumCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommonAreaDto>> {
        const response = await this.apiCommonAreaCondominiumCondominiumIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCommonAreaIdGetRaw(requestParameters: ApiCommonAreaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonAreaDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCommonAreaIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonAreaDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiCommonAreaIdGet(requestParameters: ApiCommonAreaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonAreaDto> {
        const response = await this.apiCommonAreaIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCommonAreaPhotosPhotoIdDeleteRaw(requestParameters: ApiCommonAreaPhotosPhotoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['photoId'] == null) {
            throw new runtime.RequiredError(
                'photoId',
                'Required parameter "photoId" was null or undefined when calling apiCommonAreaPhotosPhotoIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea/Photos/{photoId}`;
        urlPath = urlPath.replace(`{${"photoId"}}`, encodeURIComponent(String(requestParameters['photoId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCommonAreaPhotosPhotoIdDelete(requestParameters: ApiCommonAreaPhotosPhotoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCommonAreaPhotosPhotoIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiCommonAreaPhotosPhotoIdGetRaw(requestParameters: ApiCommonAreaPhotosPhotoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonAreaPhotoDto>> {
        if (requestParameters['photoId'] == null) {
            throw new runtime.RequiredError(
                'photoId',
                'Required parameter "photoId" was null or undefined when calling apiCommonAreaPhotosPhotoIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeData'] != null) {
            queryParameters['includeData'] = requestParameters['includeData'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea/Photos/{photoId}`;
        urlPath = urlPath.replace(`{${"photoId"}}`, encodeURIComponent(String(requestParameters['photoId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonAreaPhotoDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiCommonAreaPhotosPhotoIdGet(requestParameters: ApiCommonAreaPhotosPhotoIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonAreaPhotoDto> {
        const response = await this.apiCommonAreaPhotosPhotoIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCommonAreaPhotosPhotoIdRawGetRaw(requestParameters: ApiCommonAreaPhotosPhotoIdRawGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['photoId'] == null) {
            throw new runtime.RequiredError(
                'photoId',
                'Required parameter "photoId" was null or undefined when calling apiCommonAreaPhotosPhotoIdRawGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea/Photos/{photoId}/Raw`;
        urlPath = urlPath.replace(`{${"photoId"}}`, encodeURIComponent(String(requestParameters['photoId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCommonAreaPhotosPhotoIdRawGet(requestParameters: ApiCommonAreaPhotosPhotoIdRawGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCommonAreaPhotosPhotoIdRawGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiCommonAreaPhotosUploadPostRaw(requestParameters: ApiCommonAreaPhotosUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea/Photos/Upload`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UploadCommonAreaPhotoInputToJSON(requestParameters['uploadCommonAreaPhotoInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCommonAreaPhotosUploadPost(requestParameters: ApiCommonAreaPhotosUploadPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCommonAreaPhotosUploadPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiCommonAreaUpsertPostRaw(requestParameters: ApiCommonAreaUpsertPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea/Upsert`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpsertCommonAreaInputToJSON(requestParameters['upsertCommonAreaInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCommonAreaUpsertPost(requestParameters: ApiCommonAreaUpsertPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCommonAreaUpsertPostRaw(requestParameters, initOverrides);
    }

}
