/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommonAreaDto,
  UploadCommonAreaPhotoInput,
  UpsertCommonAreaInput,
} from '../models/index';
import {
    CommonAreaDtoFromJSON,
    CommonAreaDtoToJSON,
    UploadCommonAreaPhotoInputFromJSON,
    UploadCommonAreaPhotoInputToJSON,
    UpsertCommonAreaInputFromJSON,
    UpsertCommonAreaInputToJSON,
} from '../models/index';

export interface ApiCommonAreaCondominiumCondominiumIdGetRequest {
    condominiumId: number;
}

export interface ApiCommonAreaIdGetRequest {
    id: number;
}

export interface ApiCommonAreaIdPutRequest {
    id: number;
    upsertCommonAreaInput?: UpsertCommonAreaInput;
}

export interface ApiCommonAreaPhotosPhotoIdDeleteRequest {
    photoId: number;
}

export interface ApiCommonAreaPhotosUploadPostRequest {
    uploadCommonAreaPhotoInput?: UploadCommonAreaPhotoInput;
}

export interface ApiCommonAreaPostRequest {
    upsertCommonAreaInput?: UpsertCommonAreaInput;
}

/**
 * 
 */
export class CommonAreaApi extends runtime.BaseAPI {

    /**
     */
    async apiCommonAreaCondominiumCondominiumIdGetRaw(requestParameters: ApiCommonAreaCondominiumCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CommonAreaDto>>> {
        if (requestParameters['condominiumId'] == null) {
            throw new runtime.RequiredError(
                'condominiumId',
                'Required parameter "condominiumId" was null or undefined when calling apiCommonAreaCondominiumCondominiumIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea/Condominium/{condominiumId}`;
        urlPath = urlPath.replace(`{${"condominiumId"}}`, encodeURIComponent(String(requestParameters['condominiumId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CommonAreaDtoFromJSON));
    }

    /**
     */
    async apiCommonAreaCondominiumCondominiumIdGet(requestParameters: ApiCommonAreaCondominiumCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CommonAreaDto>> {
        const response = await this.apiCommonAreaCondominiumCondominiumIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCommonAreaIdGetRaw(requestParameters: ApiCommonAreaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonAreaDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCommonAreaIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonAreaDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiCommonAreaIdGet(requestParameters: ApiCommonAreaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonAreaDto> {
        const response = await this.apiCommonAreaIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCommonAreaIdPutRaw(requestParameters: ApiCommonAreaIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiCommonAreaIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpsertCommonAreaInputToJSON(requestParameters['upsertCommonAreaInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCommonAreaIdPut(requestParameters: ApiCommonAreaIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCommonAreaIdPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiCommonAreaPhotosPhotoIdDeleteRaw(requestParameters: ApiCommonAreaPhotosPhotoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['photoId'] == null) {
            throw new runtime.RequiredError(
                'photoId',
                'Required parameter "photoId" was null or undefined when calling apiCommonAreaPhotosPhotoIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea/Photos/{photoId}`;
        urlPath = urlPath.replace(`{${"photoId"}}`, encodeURIComponent(String(requestParameters['photoId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCommonAreaPhotosPhotoIdDelete(requestParameters: ApiCommonAreaPhotosPhotoIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCommonAreaPhotosPhotoIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiCommonAreaPhotosUploadPostRaw(requestParameters: ApiCommonAreaPhotosUploadPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea/Photos/Upload`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UploadCommonAreaPhotoInputToJSON(requestParameters['uploadCommonAreaPhotoInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCommonAreaPhotosUploadPost(requestParameters: ApiCommonAreaPhotosUploadPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCommonAreaPhotosUploadPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiCommonAreaPostRaw(requestParameters: ApiCommonAreaPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/CommonArea`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UpsertCommonAreaInputToJSON(requestParameters['upsertCommonAreaInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCommonAreaPost(requestParameters: ApiCommonAreaPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCommonAreaPostRaw(requestParameters, initOverrides);
    }

}
