/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AddUserToCondominiumInput,
  CreateOrEditCondominiumInput,
  UsuarioCondominioDto,
  UsuarioDto,
} from '../models/index';
import {
    AddUserToCondominiumInputFromJSON,
    AddUserToCondominiumInputToJSON,
    CreateOrEditCondominiumInputFromJSON,
    CreateOrEditCondominiumInputToJSON,
    UsuarioCondominioDtoFromJSON,
    UsuarioCondominioDtoToJSON,
    UsuarioDtoFromJSON,
    UsuarioDtoToJSON,
} from '../models/index';

export interface ApiCondominiumAddUserToCondominiumPostRequest {
    addUserToCondominiumInput?: AddUserToCondominiumInput;
}

export interface ApiCondominiumCondominioIdUsersGetRequest {
    condominioId: number;
}

export interface ApiCondominiumCreateOrEditPostRequest {
    createOrEditCondominiumInput?: CreateOrEditCondominiumInput;
}

export interface ApiCondominiumGetAllUserIdGetRequest {
    userId: number;
}

/**
 * 
 */
export class CondominiumApi extends runtime.BaseAPI {

    /**
     */
    async apiCondominiumAddUserToCondominiumPostRaw(requestParameters: ApiCondominiumAddUserToCondominiumPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Condominium/AddUserToCondominium`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AddUserToCondominiumInputToJSON(requestParameters['addUserToCondominiumInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCondominiumAddUserToCondominiumPost(requestParameters: ApiCondominiumAddUserToCondominiumPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCondominiumAddUserToCondominiumPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiCondominiumCondominioIdUsersGetRaw(requestParameters: ApiCondominiumCondominioIdUsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UsuarioDto>>> {
        if (requestParameters['condominioId'] == null) {
            throw new runtime.RequiredError(
                'condominioId',
                'Required parameter "condominioId" was null or undefined when calling apiCondominiumCondominioIdUsersGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Condominium/{condominioId}/Users`;
        urlPath = urlPath.replace(`{${"condominioId"}}`, encodeURIComponent(String(requestParameters['condominioId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UsuarioDtoFromJSON));
    }

    /**
     */
    async apiCondominiumCondominioIdUsersGet(requestParameters: ApiCondominiumCondominioIdUsersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UsuarioDto>> {
        const response = await this.apiCondominiumCondominioIdUsersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCondominiumCreateOrEditPostRaw(requestParameters: ApiCondominiumCreateOrEditPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Condominium/CreateOrEdit`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateOrEditCondominiumInputToJSON(requestParameters['createOrEditCondominiumInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiCondominiumCreateOrEditPost(requestParameters: ApiCondominiumCreateOrEditPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiCondominiumCreateOrEditPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiCondominiumGetAllUserIdGetRaw(requestParameters: ApiCondominiumGetAllUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<UsuarioCondominioDto>>> {
        if (requestParameters['userId'] == null) {
            throw new runtime.RequiredError(
                'userId',
                'Required parameter "userId" was null or undefined when calling apiCondominiumGetAllUserIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Condominium/GetAll/{userId}`;
        urlPath = urlPath.replace(`{${"userId"}}`, encodeURIComponent(String(requestParameters['userId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UsuarioCondominioDtoFromJSON));
    }

    /**
     */
    async apiCondominiumGetAllUserIdGet(requestParameters: ApiCondominiumGetAllUserIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UsuarioCondominioDto>> {
        const response = await this.apiCondominiumGetAllUserIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
