/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AcceptInviteRequest,
  AcceptInviteResponse,
  GenerateInviteRequest,
  GenerateInviteResponse,
} from '../models/index';
import {
    AcceptInviteRequestFromJSON,
    AcceptInviteRequestToJSON,
    AcceptInviteResponseFromJSON,
    AcceptInviteResponseToJSON,
    GenerateInviteRequestFromJSON,
    GenerateInviteRequestToJSON,
    GenerateInviteResponseFromJSON,
    GenerateInviteResponseToJSON,
} from '../models/index';

export interface ApiCondominiumAcceptInvitePostRequest {
    acceptInviteRequest?: AcceptInviteRequest;
}

export interface ApiCondominiumInvitesPostRequest {
    generateInviteRequest?: GenerateInviteRequest;
}

/**
 * 
 */
export class CondominiumInviteApi extends runtime.BaseAPI {

    /**
     */
    async apiCondominiumAcceptInvitePostRaw(requestParameters: ApiCondominiumAcceptInvitePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AcceptInviteResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Condominium/AcceptInvite`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AcceptInviteRequestToJSON(requestParameters['acceptInviteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AcceptInviteResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCondominiumAcceptInvitePost(requestParameters: ApiCondominiumAcceptInvitePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AcceptInviteResponse> {
        const response = await this.apiCondominiumAcceptInvitePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiCondominiumInvitesPostRaw(requestParameters: ApiCondominiumInvitesPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GenerateInviteResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Condominium/Invites`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GenerateInviteRequestToJSON(requestParameters['generateInviteRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GenerateInviteResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiCondominiumInvitesPost(requestParameters: ApiCondominiumInvitesPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GenerateInviteResponse> {
        const response = await this.apiCondominiumInvitesPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
