/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreatePackageInput,
  PackageDto,
  UpdatePackageInput,
  UpdatePackageStatusInput,
} from '../models/index';
import {
    CreatePackageInputFromJSON,
    CreatePackageInputToJSON,
    PackageDtoFromJSON,
    PackageDtoToJSON,
    UpdatePackageInputFromJSON,
    UpdatePackageInputToJSON,
    UpdatePackageStatusInputFromJSON,
    UpdatePackageStatusInputToJSON,
} from '../models/index';

export interface ApiPackageCondominiumCondominiumIdGetRequest {
    condominiumId: number;
}

export interface ApiPackageIdDeleteRequest {
    id: number;
}

export interface ApiPackageIdGetRequest {
    id: number;
}

export interface ApiPackageIdPutRequest {
    id: number;
    updatePackageInput?: UpdatePackageInput;
}

export interface ApiPackageIdUpdateStatusPatchRequest {
    id: number;
    updatePackageStatusInput?: UpdatePackageStatusInput;
}

export interface ApiPackageLinkResidentialLinkIdGetRequest {
    residentialLinkId: number;
}

export interface ApiPackagePostRequest {
    createPackageInput?: CreatePackageInput;
}

/**
 * 
 */
export class PackageApi extends runtime.BaseAPI {

    /**
     */
    async apiPackageCondominiumCondominiumIdGetRaw(requestParameters: ApiPackageCondominiumCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PackageDto>>> {
        if (requestParameters['condominiumId'] == null) {
            throw new runtime.RequiredError(
                'condominiumId',
                'Required parameter "condominiumId" was null or undefined when calling apiPackageCondominiumCondominiumIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Package/Condominium/{condominiumId}`;
        urlPath = urlPath.replace(`{${"condominiumId"}}`, encodeURIComponent(String(requestParameters['condominiumId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PackageDtoFromJSON));
    }

    /**
     */
    async apiPackageCondominiumCondominiumIdGet(requestParameters: ApiPackageCondominiumCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PackageDto>> {
        const response = await this.apiPackageCondominiumCondominiumIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPackageIdDeleteRaw(requestParameters: ApiPackageIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPackageIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Package/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPackageIdDelete(requestParameters: ApiPackageIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPackageIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPackageIdGetRaw(requestParameters: ApiPackageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PackageDto>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPackageIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Package/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PackageDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiPackageIdGet(requestParameters: ApiPackageIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PackageDto> {
        const response = await this.apiPackageIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPackageIdPutRaw(requestParameters: ApiPackageIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPackageIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Package/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePackageInputToJSON(requestParameters['updatePackageInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPackageIdPut(requestParameters: ApiPackageIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPackageIdPutRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPackageIdUpdateStatusPatchRaw(requestParameters: ApiPackageIdUpdateStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiPackageIdUpdateStatusPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Package/{id}/UpdateStatus`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdatePackageStatusInputToJSON(requestParameters['updatePackageStatusInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPackageIdUpdateStatusPatch(requestParameters: ApiPackageIdUpdateStatusPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPackageIdUpdateStatusPatchRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiPackageLinkResidentialLinkIdGetRaw(requestParameters: ApiPackageLinkResidentialLinkIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<PackageDto>>> {
        if (requestParameters['residentialLinkId'] == null) {
            throw new runtime.RequiredError(
                'residentialLinkId',
                'Required parameter "residentialLinkId" was null or undefined when calling apiPackageLinkResidentialLinkIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Package/Link/{residentialLinkId}`;
        urlPath = urlPath.replace(`{${"residentialLinkId"}}`, encodeURIComponent(String(requestParameters['residentialLinkId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PackageDtoFromJSON));
    }

    /**
     */
    async apiPackageLinkResidentialLinkIdGet(requestParameters: ApiPackageLinkResidentialLinkIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<PackageDto>> {
        const response = await this.apiPackageLinkResidentialLinkIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiPackagePostRaw(requestParameters: ApiPackagePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Package`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePackageInputToJSON(requestParameters['createPackageInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiPackagePost(requestParameters: ApiPackagePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiPackagePostRaw(requestParameters, initOverrides);
    }

}
