/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApproveOrRejectReservationInput,
  CreateReservationInput,
  ReservationDto,
} from '../models/index';
import {
    ApproveOrRejectReservationInputFromJSON,
    ApproveOrRejectReservationInputToJSON,
    CreateReservationInputFromJSON,
    CreateReservationInputToJSON,
    ReservationDtoFromJSON,
    ReservationDtoToJSON,
} from '../models/index';

export interface ApiReservationApproveOrRejectPostRequest {
    approveOrRejectReservationInput?: ApproveOrRejectReservationInput;
}

export interface ApiReservationAreaAreaIdGetRequest {
    areaId: number;
    start?: Date;
    end?: Date;
}

export interface ApiReservationPendingCondominiumIdGetRequest {
    condominiumId: number;
}

export interface ApiReservationPostRequest {
    createReservationInput?: CreateReservationInput;
}

export interface ApiReservationReservationIdCancelPostRequest {
    reservationId: number;
}

/**
 * 
 */
export class ReservationApi extends runtime.BaseAPI {

    /**
     */
    async apiReservationApproveOrRejectPostRaw(requestParameters: ApiReservationApproveOrRejectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Reservation/ApproveOrReject`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApproveOrRejectReservationInputToJSON(requestParameters['approveOrRejectReservationInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiReservationApproveOrRejectPost(requestParameters: ApiReservationApproveOrRejectPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiReservationApproveOrRejectPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiReservationAreaAreaIdGetRaw(requestParameters: ApiReservationAreaAreaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReservationDto>>> {
        if (requestParameters['areaId'] == null) {
            throw new runtime.RequiredError(
                'areaId',
                'Required parameter "areaId" was null or undefined when calling apiReservationAreaAreaIdGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['end'] != null) {
            queryParameters['end'] = requestParameters['end'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Reservation/Area/{areaId}`;
        urlPath = urlPath.replace(`{${"areaId"}}`, encodeURIComponent(String(requestParameters['areaId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReservationDtoFromJSON));
    }

    /**
     */
    async apiReservationAreaAreaIdGet(requestParameters: ApiReservationAreaAreaIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReservationDto>> {
        const response = await this.apiReservationAreaAreaIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiReservationPendingCondominiumIdGetRaw(requestParameters: ApiReservationPendingCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ReservationDto>>> {
        if (requestParameters['condominiumId'] == null) {
            throw new runtime.RequiredError(
                'condominiumId',
                'Required parameter "condominiumId" was null or undefined when calling apiReservationPendingCondominiumIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Reservation/Pending/{condominiumId}`;
        urlPath = urlPath.replace(`{${"condominiumId"}}`, encodeURIComponent(String(requestParameters['condominiumId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ReservationDtoFromJSON));
    }

    /**
     */
    async apiReservationPendingCondominiumIdGet(requestParameters: ApiReservationPendingCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ReservationDto>> {
        const response = await this.apiReservationPendingCondominiumIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiReservationPostRaw(requestParameters: ApiReservationPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Reservation`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateReservationInputToJSON(requestParameters['createReservationInput']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiReservationPost(requestParameters: ApiReservationPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiReservationPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiReservationReservationIdCancelPostRaw(requestParameters: ApiReservationReservationIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['reservationId'] == null) {
            throw new runtime.RequiredError(
                'reservationId',
                'Required parameter "reservationId" was null or undefined when calling apiReservationReservationIdCancelPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/Reservation/{reservationId}/Cancel`;
        urlPath = urlPath.replace(`{${"reservationId"}}`, encodeURIComponent(String(requestParameters['reservationId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiReservationReservationIdCancelPost(requestParameters: ApiReservationReservationIdCancelPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiReservationReservationIdCancelPostRaw(requestParameters, initOverrides);
    }

}
