/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateResidentialLinkRequest,
  ResidentialLinkDto,
  ReviewResidentialLinkRequest,
} from '../models/index';
import {
    CreateResidentialLinkRequestFromJSON,
    CreateResidentialLinkRequestToJSON,
    ResidentialLinkDtoFromJSON,
    ResidentialLinkDtoToJSON,
    ReviewResidentialLinkRequestFromJSON,
    ReviewResidentialLinkRequestToJSON,
} from '../models/index';

export interface ApiResidentialLinksActiveCondominiumIdGetRequest {
    condominiumId: number;
}

export interface ApiResidentialLinksMyCondominiumIdGetRequest {
    condominiumId: number;
}

export interface ApiResidentialLinksPendingCondominiumIdGetRequest {
    condominiumId: number;
}

export interface ApiResidentialLinksRequestPostRequest {
    createResidentialLinkRequest?: CreateResidentialLinkRequest;
}

export interface ApiResidentialLinksReviewPostRequest {
    reviewResidentialLinkRequest?: ReviewResidentialLinkRequest;
}

/**
 * 
 */
export class ResidentialLinksApi extends runtime.BaseAPI {

    /**
     */
    async apiResidentialLinksActiveCondominiumIdGetRaw(requestParameters: ApiResidentialLinksActiveCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ResidentialLinkDto>>> {
        if (requestParameters['condominiumId'] == null) {
            throw new runtime.RequiredError(
                'condominiumId',
                'Required parameter "condominiumId" was null or undefined when calling apiResidentialLinksActiveCondominiumIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/ResidentialLinks/active/{condominiumId}`;
        urlPath = urlPath.replace(`{${"condominiumId"}}`, encodeURIComponent(String(requestParameters['condominiumId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ResidentialLinkDtoFromJSON));
    }

    /**
     */
    async apiResidentialLinksActiveCondominiumIdGet(requestParameters: ApiResidentialLinksActiveCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ResidentialLinkDto>> {
        const response = await this.apiResidentialLinksActiveCondominiumIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiResidentialLinksMyCondominiumIdGetRaw(requestParameters: ApiResidentialLinksMyCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResidentialLinkDto>> {
        if (requestParameters['condominiumId'] == null) {
            throw new runtime.RequiredError(
                'condominiumId',
                'Required parameter "condominiumId" was null or undefined when calling apiResidentialLinksMyCondominiumIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/ResidentialLinks/my/{condominiumId}`;
        urlPath = urlPath.replace(`{${"condominiumId"}}`, encodeURIComponent(String(requestParameters['condominiumId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResidentialLinkDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiResidentialLinksMyCondominiumIdGet(requestParameters: ApiResidentialLinksMyCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResidentialLinkDto> {
        const response = await this.apiResidentialLinksMyCondominiumIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiResidentialLinksPendingCondominiumIdGetRaw(requestParameters: ApiResidentialLinksPendingCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ResidentialLinkDto>>> {
        if (requestParameters['condominiumId'] == null) {
            throw new runtime.RequiredError(
                'condominiumId',
                'Required parameter "condominiumId" was null or undefined when calling apiResidentialLinksPendingCondominiumIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/ResidentialLinks/pending/{condominiumId}`;
        urlPath = urlPath.replace(`{${"condominiumId"}}`, encodeURIComponent(String(requestParameters['condominiumId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ResidentialLinkDtoFromJSON));
    }

    /**
     */
    async apiResidentialLinksPendingCondominiumIdGet(requestParameters: ApiResidentialLinksPendingCondominiumIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ResidentialLinkDto>> {
        const response = await this.apiResidentialLinksPendingCondominiumIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiResidentialLinksRequestPostRaw(requestParameters: ApiResidentialLinksRequestPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResidentialLinkDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/ResidentialLinks/request`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateResidentialLinkRequestToJSON(requestParameters['createResidentialLinkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResidentialLinkDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiResidentialLinksRequestPost(requestParameters: ApiResidentialLinksRequestPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResidentialLinkDto> {
        const response = await this.apiResidentialLinksRequestPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiResidentialLinksReviewPostRaw(requestParameters: ApiResidentialLinksReviewPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResidentialLinkDto>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("Bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/ResidentialLinks/review`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ReviewResidentialLinkRequestToJSON(requestParameters['reviewResidentialLinkRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResidentialLinkDtoFromJSON(jsonValue));
    }

    /**
     */
    async apiResidentialLinksReviewPost(requestParameters: ApiResidentialLinksReviewPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResidentialLinkDto> {
        const response = await this.apiResidentialLinksReviewPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
