/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AcceptInviteRequest
 */
export interface AcceptInviteRequest {
    /**
     * 
     * @type {string}
     * @memberof AcceptInviteRequest
     */
    token?: string | null;
}

/**
 * Check if a given object implements the AcceptInviteRequest interface.
 */
export function instanceOfAcceptInviteRequest(value: object): value is AcceptInviteRequest {
    return true;
}

export function AcceptInviteRequestFromJSON(json: any): AcceptInviteRequest {
    return AcceptInviteRequestFromJSONTyped(json, false);
}

export function AcceptInviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptInviteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
    };
}

export function AcceptInviteRequestToJSON(json: any): AcceptInviteRequest {
    return AcceptInviteRequestToJSONTyped(json, false);
}

export function AcceptInviteRequestToJSONTyped(value?: AcceptInviteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
    };
}

