/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CondominiumDto } from './CondominiumDto';
import {
    CondominiumDtoFromJSON,
    CondominiumDtoFromJSONTyped,
    CondominiumDtoToJSON,
    CondominiumDtoToJSONTyped,
} from './CondominiumDto';
import type { ETipoUsuario } from './ETipoUsuario';
import {
    ETipoUsuarioFromJSON,
    ETipoUsuarioFromJSONTyped,
    ETipoUsuarioToJSON,
    ETipoUsuarioToJSONTyped,
} from './ETipoUsuario';

/**
 * 
 * @export
 * @interface AcceptInviteResponse
 */
export interface AcceptInviteResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AcceptInviteResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ETipoUsuario}
     * @memberof AcceptInviteResponse
     */
    role?: ETipoUsuario;
    /**
     * 
     * @type {CondominiumDto}
     * @memberof AcceptInviteResponse
     */
    condominium?: CondominiumDto;
    /**
     * 
     * @type {string}
     * @memberof AcceptInviteResponse
     */
    message?: string | null;
}



/**
 * Check if a given object implements the AcceptInviteResponse interface.
 */
export function instanceOfAcceptInviteResponse(value: object): value is AcceptInviteResponse {
    return true;
}

export function AcceptInviteResponseFromJSON(json: any): AcceptInviteResponse {
    return AcceptInviteResponseFromJSONTyped(json, false);
}

export function AcceptInviteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptInviteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'role': json['role'] == null ? undefined : ETipoUsuarioFromJSON(json['role']),
        'condominium': json['condominium'] == null ? undefined : CondominiumDtoFromJSON(json['condominium']),
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function AcceptInviteResponseToJSON(json: any): AcceptInviteResponse {
    return AcceptInviteResponseToJSONTyped(json, false);
}

export function AcceptInviteResponseToJSONTyped(value?: AcceptInviteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'role': ETipoUsuarioToJSON(value['role']),
        'condominium': CondominiumDtoToJSON(value['condominium']),
        'message': value['message'],
    };
}

