/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ETipoUsuario } from './ETipoUsuario';
import {
    ETipoUsuarioFromJSON,
    ETipoUsuarioFromJSONTyped,
    ETipoUsuarioToJSON,
    ETipoUsuarioToJSONTyped,
} from './ETipoUsuario';

/**
 * 
 * @export
 * @interface AddUserToCondominiumInput
 */
export interface AddUserToCondominiumInput {
    /**
     * 
     * @type {number}
     * @memberof AddUserToCondominiumInput
     */
    condominiumId?: number;
    /**
     * 
     * @type {number}
     * @memberof AddUserToCondominiumInput
     */
    userId?: number;
    /**
     * 
     * @type {ETipoUsuario}
     * @memberof AddUserToCondominiumInput
     */
    userType?: ETipoUsuario;
    /**
     * 
     * @type {boolean}
     * @memberof AddUserToCondominiumInput
     */
    active?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AddUserToCondominiumInput
     */
    startDate?: Date | null;
}



/**
 * Check if a given object implements the AddUserToCondominiumInput interface.
 */
export function instanceOfAddUserToCondominiumInput(value: object): value is AddUserToCondominiumInput {
    return true;
}

export function AddUserToCondominiumInputFromJSON(json: any): AddUserToCondominiumInput {
    return AddUserToCondominiumInputFromJSONTyped(json, false);
}

export function AddUserToCondominiumInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserToCondominiumInput {
    if (json == null) {
        return json;
    }
    return {
        
        'condominiumId': json['condominiumId'] == null ? undefined : json['condominiumId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userType': json['userType'] == null ? undefined : ETipoUsuarioFromJSON(json['userType']),
        'active': json['active'] == null ? undefined : json['active'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
    };
}

export function AddUserToCondominiumInputToJSON(json: any): AddUserToCondominiumInput {
    return AddUserToCondominiumInputToJSONTyped(json, false);
}

export function AddUserToCondominiumInputToJSONTyped(value?: AddUserToCondominiumInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'condominiumId': value['condominiumId'],
        'userId': value['userId'],
        'userType': ETipoUsuarioToJSON(value['userType']),
        'active': value['active'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
    };
}

