/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ETipoUsuario } from './ETipoUsuario';
import {
    ETipoUsuarioFromJSON,
    ETipoUsuarioFromJSONTyped,
    ETipoUsuarioToJSON,
    ETipoUsuarioToJSONTyped,
} from './ETipoUsuario';

/**
 * 
 * @export
 * @interface AddUserToCondominiumInput
 */
export interface AddUserToCondominiumInput {
    /**
     * 
     * @type {number}
     * @memberof AddUserToCondominiumInput
     */
    condominioId?: number;
    /**
     * 
     * @type {number}
     * @memberof AddUserToCondominiumInput
     */
    usuarioId?: number;
    /**
     * 
     * @type {ETipoUsuario}
     * @memberof AddUserToCondominiumInput
     */
    tipoUsuario?: ETipoUsuario;
    /**
     * 
     * @type {boolean}
     * @memberof AddUserToCondominiumInput
     */
    ativo?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof AddUserToCondominiumInput
     */
    dataInicio?: Date | null;
}



/**
 * Check if a given object implements the AddUserToCondominiumInput interface.
 */
export function instanceOfAddUserToCondominiumInput(value: object): value is AddUserToCondominiumInput {
    return true;
}

export function AddUserToCondominiumInputFromJSON(json: any): AddUserToCondominiumInput {
    return AddUserToCondominiumInputFromJSONTyped(json, false);
}

export function AddUserToCondominiumInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddUserToCondominiumInput {
    if (json == null) {
        return json;
    }
    return {
        
        'condominioId': json['condominioId'] == null ? undefined : json['condominioId'],
        'usuarioId': json['usuarioId'] == null ? undefined : json['usuarioId'],
        'tipoUsuario': json['tipoUsuario'] == null ? undefined : ETipoUsuarioFromJSON(json['tipoUsuario']),
        'ativo': json['ativo'] == null ? undefined : json['ativo'],
        'dataInicio': json['dataInicio'] == null ? undefined : (new Date(json['dataInicio'])),
    };
}

export function AddUserToCondominiumInputToJSON(json: any): AddUserToCondominiumInput {
    return AddUserToCondominiumInputToJSONTyped(json, false);
}

export function AddUserToCondominiumInputToJSONTyped(value?: AddUserToCondominiumInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'condominioId': value['condominioId'],
        'usuarioId': value['usuarioId'],
        'tipoUsuario': ETipoUsuarioToJSON(value['tipoUsuario']),
        'ativo': value['ativo'],
        'dataInicio': value['dataInicio'] == null ? value['dataInicio'] : value['dataInicio'].toISOString(),
    };
}

