/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApartmentInputDto
 */
export interface ApartmentInputDto {
    /**
     * 
     * @type {number}
     * @memberof ApartmentInputDto
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ApartmentInputDto
     */
    number?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApartmentInputDto
     */
    floorNumber?: number;
}

/**
 * Check if a given object implements the ApartmentInputDto interface.
 */
export function instanceOfApartmentInputDto(value: object): value is ApartmentInputDto {
    return true;
}

export function ApartmentInputDtoFromJSON(json: any): ApartmentInputDto {
    return ApartmentInputDtoFromJSONTyped(json, false);
}

export function ApartmentInputDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApartmentInputDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'number': json['number'] == null ? undefined : json['number'],
        'floorNumber': json['floorNumber'] == null ? undefined : json['floorNumber'],
    };
}

export function ApartmentInputDtoToJSON(json: any): ApartmentInputDto {
    return ApartmentInputDtoToJSONTyped(json, false);
}

export function ApartmentInputDtoToJSONTyped(value?: ApartmentInputDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'number': value['number'],
        'floorNumber': value['floorNumber'],
    };
}

