/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApartmentDto
 */
export interface ApartmentDto {
    /**
     * 
     * @type {number}
     * @memberof ApartmentDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof ApartmentDto
     */
    number?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApartmentDto
     */
    floorNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ApartmentDto
     */
    blockId?: number;
}

/**
 * Check if a given object implements the ApartmentDto interface.
 */
export function instanceOfApartmentDto(value: object): value is ApartmentDto {
    return true;
}

export function ApartmentDtoFromJSON(json: any): ApartmentDto {
    return ApartmentDtoFromJSONTyped(json, false);
}

export function ApartmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApartmentDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'number': json['number'] == null ? undefined : json['number'],
        'floorNumber': json['floorNumber'] == null ? undefined : json['floorNumber'],
        'blockId': json['blockId'] == null ? undefined : json['blockId'],
    };
}

export function ApartmentDtoToJSON(json: any): ApartmentDto {
    return ApartmentDtoToJSONTyped(json, false);
}

export function ApartmentDtoToJSONTyped(value?: ApartmentDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'number': value['number'],
        'floorNumber': value['floorNumber'],
        'blockId': value['blockId'],
    };
}

