/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApproveRequest
 */
export interface ApproveRequest {
    /**
     * 
     * @type {boolean}
     * @memberof ApproveRequest
     */
    approve?: boolean;
}

/**
 * Check if a given object implements the ApproveRequest interface.
 */
export function instanceOfApproveRequest(value: object): value is ApproveRequest {
    return true;
}

export function ApproveRequestFromJSON(json: any): ApproveRequest {
    return ApproveRequestFromJSONTyped(json, false);
}

export function ApproveRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApproveRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'approve': json['approve'] == null ? undefined : json['approve'],
    };
}

export function ApproveRequestToJSON(json: any): ApproveRequest {
    return ApproveRequestToJSONTyped(json, false);
}

export function ApproveRequestToJSONTyped(value?: ApproveRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'approve': value['approve'],
    };
}

