/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApproveOrRejectReservationInput
 */
export interface ApproveOrRejectReservationInput {
    /**
     * 
     * @type {number}
     * @memberof ApproveOrRejectReservationInput
     */
    reservationId?: number;
    /**
     * 
     * @type {number}
     * @memberof ApproveOrRejectReservationInput
     */
    userId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ApproveOrRejectReservationInput
     */
    shouldApprove?: boolean;
}

/**
 * Check if a given object implements the ApproveOrRejectReservationInput interface.
 */
export function instanceOfApproveOrRejectReservationInput(value: object): value is ApproveOrRejectReservationInput {
    return true;
}

export function ApproveOrRejectReservationInputFromJSON(json: any): ApproveOrRejectReservationInput {
    return ApproveOrRejectReservationInputFromJSONTyped(json, false);
}

export function ApproveOrRejectReservationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApproveOrRejectReservationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'reservationId': json['reservationId'] == null ? undefined : json['reservationId'],
        'userId': json['userId'] == null ? undefined : json['userId'],
        'shouldApprove': json['shouldApprove'] == null ? undefined : json['shouldApprove'],
    };
}

export function ApproveOrRejectReservationInputToJSON(json: any): ApproveOrRejectReservationInput {
    return ApproveOrRejectReservationInputToJSONTyped(json, false);
}

export function ApproveOrRejectReservationInputToJSONTyped(value?: ApproveOrRejectReservationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'reservationId': value['reservationId'],
        'userId': value['userId'],
        'shouldApprove': value['shouldApprove'],
    };
}

