/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDto } from './UserDto';
import {
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
    UserDtoToJSONTyped,
} from './UserDto';

/**
 * 
 * @export
 * @interface AuthenticationResponse
 */
export interface AuthenticationResponse {
    /**
     * 
     * @type {UserDto}
     * @memberof AuthenticationResponse
     */
    usuario?: UserDto;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationResponse
     */
    token?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AuthenticationResponse
     */
    sucesso?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthenticationResponse
     */
    erro?: string | null;
}

/**
 * Check if a given object implements the AuthenticationResponse interface.
 */
export function instanceOfAuthenticationResponse(value: object): value is AuthenticationResponse {
    return true;
}

export function AuthenticationResponseFromJSON(json: any): AuthenticationResponse {
    return AuthenticationResponseFromJSONTyped(json, false);
}

export function AuthenticationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'usuario': json['usuario'] == null ? undefined : UserDtoFromJSON(json['usuario']),
        'token': json['token'] == null ? undefined : json['token'],
        'sucesso': json['sucesso'] == null ? undefined : json['sucesso'],
        'erro': json['erro'] == null ? undefined : json['erro'],
    };
}

export function AuthenticationResponseToJSON(json: any): AuthenticationResponse {
    return AuthenticationResponseToJSONTyped(json, false);
}

export function AuthenticationResponseToJSONTyped(value?: AuthenticationResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usuario': UserDtoToJSON(value['usuario']),
        'token': value['token'],
        'sucesso': value['sucesso'],
        'erro': value['erro'],
    };
}

