/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApartmentInputDto } from './ApartmentInputDto';
import {
    ApartmentInputDtoFromJSON,
    ApartmentInputDtoFromJSONTyped,
    ApartmentInputDtoToJSON,
    ApartmentInputDtoToJSONTyped,
} from './ApartmentInputDto';

/**
 * 
 * @export
 * @interface BlockInputDto
 */
export interface BlockInputDto {
    /**
     * 
     * @type {number}
     * @memberof BlockInputDto
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof BlockInputDto
     */
    name?: string | null;
    /**
     * 
     * @type {Array<ApartmentInputDto>}
     * @memberof BlockInputDto
     */
    apartments?: Array<ApartmentInputDto> | null;
}

/**
 * Check if a given object implements the BlockInputDto interface.
 */
export function instanceOfBlockInputDto(value: object): value is BlockInputDto {
    return true;
}

export function BlockInputDtoFromJSON(json: any): BlockInputDto {
    return BlockInputDtoFromJSONTyped(json, false);
}

export function BlockInputDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockInputDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'apartments': json['apartments'] == null ? undefined : ((json['apartments'] as Array<any>).map(ApartmentInputDtoFromJSON)),
    };
}

export function BlockInputDtoToJSON(json: any): BlockInputDto {
    return BlockInputDtoToJSONTyped(json, false);
}

export function BlockInputDtoToJSONTyped(value?: BlockInputDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'apartments': value['apartments'] == null ? undefined : ((value['apartments'] as Array<any>).map(ApartmentInputDtoToJSON)),
    };
}

