/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordInput
 */
export interface ChangePasswordInput {
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordInput
     */
    password?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ChangePasswordInput
     */
    userId?: number;
}

/**
 * Check if a given object implements the ChangePasswordInput interface.
 */
export function instanceOfChangePasswordInput(value: object): value is ChangePasswordInput {
    return true;
}

export function ChangePasswordInputFromJSON(json: any): ChangePasswordInput {
    return ChangePasswordInputFromJSONTyped(json, false);
}

export function ChangePasswordInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordInput {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'] == null ? undefined : json['password'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function ChangePasswordInputToJSON(json: any): ChangePasswordInput {
    return ChangePasswordInputToJSONTyped(json, false);
}

export function ChangePasswordInputToJSONTyped(value?: ChangePasswordInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'password': value['password'],
        'userId': value['userId'],
    };
}

