/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommonAreaPhotoDto } from './CommonAreaPhotoDto';
import {
    CommonAreaPhotoDtoFromJSON,
    CommonAreaPhotoDtoFromJSONTyped,
    CommonAreaPhotoDtoToJSON,
    CommonAreaPhotoDtoToJSONTyped,
} from './CommonAreaPhotoDto';

/**
 * 
 * @export
 * @interface CommonAreaDto
 */
export interface CommonAreaDto {
    /**
     * 
     * @type {number}
     * @memberof CommonAreaDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof CommonAreaDto
     */
    condominiumId?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonAreaDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommonAreaDto
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommonAreaDto
     */
    type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CommonAreaDto
     */
    capacity?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonAreaDto
     */
    openingTime?: string;
    /**
     * 
     * @type {string}
     * @memberof CommonAreaDto
     */
    closingTime?: string;
    /**
     * 
     * @type {number}
     * @memberof CommonAreaDto
     */
    maxDuration?: number;
    /**
     * 
     * @type {boolean}
     * @memberof CommonAreaDto
     */
    available?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CommonAreaDto
     */
    requiresApproval?: boolean;
    /**
     * 
     * @type {number}
     * @memberof CommonAreaDto
     */
    availableDays?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonAreaDto
     */
    notes?: string | null;
    /**
     * 
     * @type {Array<CommonAreaPhotoDto>}
     * @memberof CommonAreaDto
     */
    photos?: Array<CommonAreaPhotoDto> | null;
}

/**
 * Check if a given object implements the CommonAreaDto interface.
 */
export function instanceOfCommonAreaDto(value: object): value is CommonAreaDto {
    return true;
}

export function CommonAreaDtoFromJSON(json: any): CommonAreaDto {
    return CommonAreaDtoFromJSONTyped(json, false);
}

export function CommonAreaDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonAreaDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'condominiumId': json['condominiumId'] == null ? undefined : json['condominiumId'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'openingTime': json['openingTime'] == null ? undefined : json['openingTime'],
        'closingTime': json['closingTime'] == null ? undefined : json['closingTime'],
        'maxDuration': json['maxDuration'] == null ? undefined : json['maxDuration'],
        'available': json['available'] == null ? undefined : json['available'],
        'requiresApproval': json['requiresApproval'] == null ? undefined : json['requiresApproval'],
        'availableDays': json['availableDays'] == null ? undefined : json['availableDays'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'photos': json['photos'] == null ? undefined : ((json['photos'] as Array<any>).map(CommonAreaPhotoDtoFromJSON)),
    };
}

export function CommonAreaDtoToJSON(json: any): CommonAreaDto {
    return CommonAreaDtoToJSONTyped(json, false);
}

export function CommonAreaDtoToJSONTyped(value?: CommonAreaDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'condominiumId': value['condominiumId'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'capacity': value['capacity'],
        'openingTime': value['openingTime'],
        'closingTime': value['closingTime'],
        'maxDuration': value['maxDuration'],
        'available': value['available'],
        'requiresApproval': value['requiresApproval'],
        'availableDays': value['availableDays'],
        'notes': value['notes'],
        'photos': value['photos'] == null ? undefined : ((value['photos'] as Array<any>).map(CommonAreaPhotoDtoToJSON)),
    };
}

