/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonAreaPhotoDto
 */
export interface CommonAreaPhotoDto {
    /**
     * 
     * @type {number}
     * @memberof CommonAreaPhotoDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonAreaPhotoDto
     */
    contentType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommonAreaPhotoDto
     */
    originalFileName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CommonAreaPhotoDto
     */
    originalSize?: number;
    /**
     * 
     * @type {string}
     * @memberof CommonAreaPhotoDto
     */
    hashSha256?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CommonAreaPhotoDto
     */
    base64Data?: string | null;
}

/**
 * Check if a given object implements the CommonAreaPhotoDto interface.
 */
export function instanceOfCommonAreaPhotoDto(value: object): value is CommonAreaPhotoDto {
    return true;
}

export function CommonAreaPhotoDtoFromJSON(json: any): CommonAreaPhotoDto {
    return CommonAreaPhotoDtoFromJSONTyped(json, false);
}

export function CommonAreaPhotoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonAreaPhotoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'contentType': json['contentType'] == null ? undefined : json['contentType'],
        'originalFileName': json['originalFileName'] == null ? undefined : json['originalFileName'],
        'originalSize': json['originalSize'] == null ? undefined : json['originalSize'],
        'hashSha256': json['hashSha256'] == null ? undefined : json['hashSha256'],
        'base64Data': json['base64Data'] == null ? undefined : json['base64Data'],
    };
}

export function CommonAreaPhotoDtoToJSON(json: any): CommonAreaPhotoDto {
    return CommonAreaPhotoDtoToJSONTyped(json, false);
}

export function CommonAreaPhotoDtoToJSONTyped(value?: CommonAreaPhotoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'contentType': value['contentType'],
        'originalFileName': value['originalFileName'],
        'originalSize': value['originalSize'],
        'hashSha256': value['hashSha256'],
        'base64Data': value['base64Data'],
    };
}

