/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressDto } from './AddressDto';
import {
    AddressDtoFromJSON,
    AddressDtoFromJSONTyped,
    AddressDtoToJSON,
    AddressDtoToJSONTyped,
} from './AddressDto';

/**
 * 
 * @export
 * @interface CondominiumDto
 */
export interface CondominiumDto {
    /**
     * 
     * @type {number}
     * @memberof CondominiumDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CondominiumDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CondominiumDto
     */
    cnpj?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CondominiumDto
     */
    email?: string | null;
    /**
     * 
     * @type {AddressDto}
     * @memberof CondominiumDto
     */
    address?: AddressDto;
}

/**
 * Check if a given object implements the CondominiumDto interface.
 */
export function instanceOfCondominiumDto(value: object): value is CondominiumDto {
    return true;
}

export function CondominiumDtoFromJSON(json: any): CondominiumDto {
    return CondominiumDtoFromJSONTyped(json, false);
}

export function CondominiumDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CondominiumDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'cnpj': json['cnpj'] == null ? undefined : json['cnpj'],
        'email': json['email'] == null ? undefined : json['email'],
        'address': json['address'] == null ? undefined : AddressDtoFromJSON(json['address']),
    };
}

export function CondominiumDtoToJSON(json: any): CondominiumDto {
    return CondominiumDtoToJSONTyped(json, false);
}

export function CondominiumDtoToJSONTyped(value?: CondominiumDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'cnpj': value['cnpj'],
        'email': value['email'],
        'address': AddressDtoToJSON(value['address']),
    };
}

