/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnderecoDto } from './EnderecoDto';
import {
    EnderecoDtoFromJSON,
    EnderecoDtoFromJSONTyped,
    EnderecoDtoToJSON,
    EnderecoDtoToJSONTyped,
} from './EnderecoDto';

/**
 * 
 * @export
 * @interface CondominioDto
 */
export interface CondominioDto {
    /**
     * 
     * @type {number}
     * @memberof CondominioDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CondominioDto
     */
    nome?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CondominioDto
     */
    cnpj?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CondominioDto
     */
    email?: string | null;
    /**
     * 
     * @type {EnderecoDto}
     * @memberof CondominioDto
     */
    endereco?: EnderecoDto;
}

/**
 * Check if a given object implements the CondominioDto interface.
 */
export function instanceOfCondominioDto(value: object): value is CondominioDto {
    return true;
}

export function CondominioDtoFromJSON(json: any): CondominioDto {
    return CondominioDtoFromJSONTyped(json, false);
}

export function CondominioDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CondominioDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'nome': json['nome'] == null ? undefined : json['nome'],
        'cnpj': json['cnpj'] == null ? undefined : json['cnpj'],
        'email': json['email'] == null ? undefined : json['email'],
        'endereco': json['endereco'] == null ? undefined : EnderecoDtoFromJSON(json['endereco']),
    };
}

export function CondominioDtoToJSON(json: any): CondominioDto {
    return CondominioDtoToJSONTyped(json, false);
}

export function CondominioDtoToJSONTyped(value?: CondominioDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nome': value['nome'],
        'cnpj': value['cnpj'],
        'email': value['email'],
        'endereco': EnderecoDtoToJSON(value['endereco']),
    };
}

