/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnderecoDto } from './EnderecoDto';
import {
    EnderecoDtoFromJSON,
    EnderecoDtoFromJSONTyped,
    EnderecoDtoToJSON,
    EnderecoDtoToJSONTyped,
} from './EnderecoDto';

/**
 * 
 * @export
 * @interface CreateOrEditCondominiumInput
 */
export interface CreateOrEditCondominiumInput {
    /**
     * 
     * @type {number}
     * @memberof CreateOrEditCondominiumInput
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrEditCondominiumInput
     */
    nome?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrEditCondominiumInput
     */
    cnpj?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrEditCondominiumInput
     */
    email?: string | null;
    /**
     * 
     * @type {EnderecoDto}
     * @memberof CreateOrEditCondominiumInput
     */
    endereco?: EnderecoDto;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateOrEditCondominiumInput
     */
    usuariosIds?: Array<number> | null;
}

/**
 * Check if a given object implements the CreateOrEditCondominiumInput interface.
 */
export function instanceOfCreateOrEditCondominiumInput(value: object): value is CreateOrEditCondominiumInput {
    return true;
}

export function CreateOrEditCondominiumInputFromJSON(json: any): CreateOrEditCondominiumInput {
    return CreateOrEditCondominiumInputFromJSONTyped(json, false);
}

export function CreateOrEditCondominiumInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrEditCondominiumInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'nome': json['nome'] == null ? undefined : json['nome'],
        'cnpj': json['cnpj'] == null ? undefined : json['cnpj'],
        'email': json['email'] == null ? undefined : json['email'],
        'endereco': json['endereco'] == null ? undefined : EnderecoDtoFromJSON(json['endereco']),
        'usuariosIds': json['usuariosIds'] == null ? undefined : json['usuariosIds'],
    };
}

export function CreateOrEditCondominiumInputToJSON(json: any): CreateOrEditCondominiumInput {
    return CreateOrEditCondominiumInputToJSONTyped(json, false);
}

export function CreateOrEditCondominiumInputToJSONTyped(value?: CreateOrEditCondominiumInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nome': value['nome'],
        'cnpj': value['cnpj'],
        'email': value['email'],
        'endereco': EnderecoDtoToJSON(value['endereco']),
        'usuariosIds': value['usuariosIds'],
    };
}

