/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReservationInput
 */
export interface CreateReservationInput {
    /**
     * 
     * @type {number}
     * @memberof CreateReservationInput
     */
    areaId?: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateReservationInput
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateReservationInput
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateReservationInput
     */
    endTime?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateReservationInput
     */
    guests?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateReservationInput
     */
    purpose?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateReservationInput
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the CreateReservationInput interface.
 */
export function instanceOfCreateReservationInput(value: object): value is CreateReservationInput {
    return true;
}

export function CreateReservationInputFromJSON(json: any): CreateReservationInput {
    return CreateReservationInputFromJSONTyped(json, false);
}

export function CreateReservationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReservationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'areaId': json['areaId'] == null ? undefined : json['areaId'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'guests': json['guests'] == null ? undefined : json['guests'],
        'purpose': json['purpose'] == null ? undefined : json['purpose'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function CreateReservationInputToJSON(json: any): CreateReservationInput {
    return CreateReservationInputToJSONTyped(json, false);
}

export function CreateReservationInputToJSONTyped(value?: CreateReservationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'areaId': value['areaId'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'guests': value['guests'],
        'purpose': value['purpose'],
        'notes': value['notes'],
    };
}

