/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateReservationInput
 */
export interface CreateReservationInput {
    /**
     * 
     * @type {number}
     * @memberof CreateReservationInput
     */
    areaId?: number;
    /**
     * 
     * @type {Date}
     * @memberof CreateReservationInput
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CreateReservationInput
     */
    endDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof CreateReservationInput
     */
    guests?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateReservationInput
     */
    purpose?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateReservationInput
     */
    notes?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateReservationInput
     */
    userId?: number;
}

/**
 * Check if a given object implements the CreateReservationInput interface.
 */
export function instanceOfCreateReservationInput(value: object): value is CreateReservationInput {
    return true;
}

export function CreateReservationInputFromJSON(json: any): CreateReservationInput {
    return CreateReservationInputFromJSONTyped(json, false);
}

export function CreateReservationInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateReservationInput {
    if (json == null) {
        return json;
    }
    return {
        
        'areaId': json['areaId'] == null ? undefined : json['areaId'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'guests': json['guests'] == null ? undefined : json['guests'],
        'purpose': json['purpose'] == null ? undefined : json['purpose'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function CreateReservationInputToJSON(json: any): CreateReservationInput {
    return CreateReservationInputToJSONTyped(json, false);
}

export function CreateReservationInputToJSONTyped(value?: CreateReservationInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'areaId': value['areaId'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'guests': value['guests'],
        'purpose': value['purpose'],
        'notes': value['notes'],
        'userId': value['userId'],
    };
}

