/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressDto } from './AddressDto';
import {
    AddressDtoFromJSON,
    AddressDtoFromJSONTyped,
    AddressDtoToJSON,
    AddressDtoToJSONTyped,
} from './AddressDto';
import type { BlockInputDto } from './BlockInputDto';
import {
    BlockInputDtoFromJSON,
    BlockInputDtoFromJSONTyped,
    BlockInputDtoToJSON,
    BlockInputDtoToJSONTyped,
} from './BlockInputDto';

/**
 * 
 * @export
 * @interface CreateOrEditCondominiumInput
 */
export interface CreateOrEditCondominiumInput {
    /**
     * 
     * @type {number}
     * @memberof CreateOrEditCondominiumInput
     */
    id?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrEditCondominiumInput
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrEditCondominiumInput
     */
    cnpj?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CreateOrEditCondominiumInput
     */
    email?: string | null;
    /**
     * 
     * @type {AddressDto}
     * @memberof CreateOrEditCondominiumInput
     */
    address?: AddressDto;
    /**
     * 
     * @type {Array<number>}
     * @memberof CreateOrEditCondominiumInput
     */
    userIds?: Array<number> | null;
    /**
     * 
     * @type {Array<BlockInputDto>}
     * @memberof CreateOrEditCondominiumInput
     */
    blocks?: Array<BlockInputDto> | null;
}

/**
 * Check if a given object implements the CreateOrEditCondominiumInput interface.
 */
export function instanceOfCreateOrEditCondominiumInput(value: object): value is CreateOrEditCondominiumInput {
    return true;
}

export function CreateOrEditCondominiumInputFromJSON(json: any): CreateOrEditCondominiumInput {
    return CreateOrEditCondominiumInputFromJSONTyped(json, false);
}

export function CreateOrEditCondominiumInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrEditCondominiumInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'cnpj': json['cnpj'] == null ? undefined : json['cnpj'],
        'email': json['email'] == null ? undefined : json['email'],
        'address': json['address'] == null ? undefined : AddressDtoFromJSON(json['address']),
        'userIds': json['userIds'] == null ? undefined : json['userIds'],
        'blocks': json['blocks'] == null ? undefined : ((json['blocks'] as Array<any>).map(BlockInputDtoFromJSON)),
    };
}

export function CreateOrEditCondominiumInputToJSON(json: any): CreateOrEditCondominiumInput {
    return CreateOrEditCondominiumInputToJSONTyped(json, false);
}

export function CreateOrEditCondominiumInputToJSONTyped(value?: CreateOrEditCondominiumInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'cnpj': value['cnpj'],
        'email': value['email'],
        'address': AddressDtoToJSON(value['address']),
        'userIds': value['userIds'],
        'blocks': value['blocks'] == null ? undefined : ((value['blocks'] as Array<any>).map(BlockInputDtoToJSON)),
    };
}

