/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ETipoOcupacao } from './ETipoOcupacao';
import {
    ETipoOcupacaoFromJSON,
    ETipoOcupacaoFromJSONTyped,
    ETipoOcupacaoToJSON,
    ETipoOcupacaoToJSONTyped,
} from './ETipoOcupacao';

/**
 * 
 * @export
 * @interface CreateResidentialLinkRequest
 */
export interface CreateResidentialLinkRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateResidentialLinkRequest
     */
    condominiumId?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateResidentialLinkRequest
     */
    apartmentNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CreateResidentialLinkRequest
     */
    blockId?: number | null;
    /**
     * 
     * @type {ETipoOcupacao}
     * @memberof CreateResidentialLinkRequest
     */
    tipoOcupacao?: ETipoOcupacao;
}



/**
 * Check if a given object implements the CreateResidentialLinkRequest interface.
 */
export function instanceOfCreateResidentialLinkRequest(value: object): value is CreateResidentialLinkRequest {
    return true;
}

export function CreateResidentialLinkRequestFromJSON(json: any): CreateResidentialLinkRequest {
    return CreateResidentialLinkRequestFromJSONTyped(json, false);
}

export function CreateResidentialLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateResidentialLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'condominiumId': json['condominiumId'] == null ? undefined : json['condominiumId'],
        'apartmentNumber': json['apartmentNumber'] == null ? undefined : json['apartmentNumber'],
        'blockId': json['blockId'] == null ? undefined : json['blockId'],
        'tipoOcupacao': json['tipoOcupacao'] == null ? undefined : ETipoOcupacaoFromJSON(json['tipoOcupacao']),
    };
}

export function CreateResidentialLinkRequestToJSON(json: any): CreateResidentialLinkRequest {
    return CreateResidentialLinkRequestToJSONTyped(json, false);
}

export function CreateResidentialLinkRequestToJSONTyped(value?: CreateResidentialLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'condominiumId': value['condominiumId'],
        'apartmentNumber': value['apartmentNumber'],
        'blockId': value['blockId'],
        'tipoOcupacao': ETipoOcupacaoToJSON(value['tipoOcupacao']),
    };
}

