/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnderecoDto
 */
export interface EnderecoDto {
    /**
     * 
     * @type {string}
     * @memberof EnderecoDto
     */
    logradouro?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnderecoDto
     */
    numero?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnderecoDto
     */
    complemento?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnderecoDto
     */
    bairro?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnderecoDto
     */
    cidade?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnderecoDto
     */
    estado?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnderecoDto
     */
    cep?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EnderecoDto
     */
    pais?: string | null;
}

/**
 * Check if a given object implements the EnderecoDto interface.
 */
export function instanceOfEnderecoDto(value: object): value is EnderecoDto {
    return true;
}

export function EnderecoDtoFromJSON(json: any): EnderecoDto {
    return EnderecoDtoFromJSONTyped(json, false);
}

export function EnderecoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnderecoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'logradouro': json['logradouro'] == null ? undefined : json['logradouro'],
        'numero': json['numero'] == null ? undefined : json['numero'],
        'complemento': json['complemento'] == null ? undefined : json['complemento'],
        'bairro': json['bairro'] == null ? undefined : json['bairro'],
        'cidade': json['cidade'] == null ? undefined : json['cidade'],
        'estado': json['estado'] == null ? undefined : json['estado'],
        'cep': json['cep'] == null ? undefined : json['cep'],
        'pais': json['pais'] == null ? undefined : json['pais'],
    };
}

export function EnderecoDtoToJSON(json: any): EnderecoDto {
    return EnderecoDtoToJSONTyped(json, false);
}

export function EnderecoDtoToJSONTyped(value?: EnderecoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'logradouro': value['logradouro'],
        'numero': value['numero'],
        'complemento': value['complemento'],
        'bairro': value['bairro'],
        'cidade': value['cidade'],
        'estado': value['estado'],
        'cep': value['cep'],
        'pais': value['pais'],
    };
}

