/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ETipoUsuario = {
    Morador: 'MORADOR',
    Sindico: 'SINDICO',
    Porteiro: 'PORTEIRO',
    Administrador: 'ADMINISTRADOR'
} as const;
export type ETipoUsuario = typeof ETipoUsuario[keyof typeof ETipoUsuario];


export function instanceOfETipoUsuario(value: any): boolean {
    for (const key in ETipoUsuario) {
        if (Object.prototype.hasOwnProperty.call(ETipoUsuario, key)) {
            if (ETipoUsuario[key as keyof typeof ETipoUsuario] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ETipoUsuarioFromJSON(json: any): ETipoUsuario {
    return ETipoUsuarioFromJSONTyped(json, false);
}

export function ETipoUsuarioFromJSONTyped(json: any, ignoreDiscriminator: boolean): ETipoUsuario {
    return json as ETipoUsuario;
}

export function ETipoUsuarioToJSON(value?: ETipoUsuario | null): any {
    return value as any;
}

export function ETipoUsuarioToJSONTyped(value: any, ignoreDiscriminator: boolean): ETipoUsuario {
    return value as ETipoUsuario;
}

