/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ETipoUsuario } from './ETipoUsuario';
import {
    ETipoUsuarioFromJSON,
    ETipoUsuarioFromJSONTyped,
    ETipoUsuarioToJSON,
    ETipoUsuarioToJSONTyped,
} from './ETipoUsuario';

/**
 * 
 * @export
 * @interface GenerateInviteRequest
 */
export interface GenerateInviteRequest {
    /**
     * 
     * @type {number}
     * @memberof GenerateInviteRequest
     */
    condominiumId?: number;
    /**
     * 
     * @type {ETipoUsuario}
     * @memberof GenerateInviteRequest
     */
    role?: ETipoUsuario;
    /**
     * 
     * @type {boolean}
     * @memberof GenerateInviteRequest
     */
    singleUse?: boolean | null;
    /**
     * 
     * @type {number}
     * @memberof GenerateInviteRequest
     */
    maxUses?: number | null;
    /**
     * 
     * @type {number}
     * @memberof GenerateInviteRequest
     */
    expiresInDays?: number | null;
}



/**
 * Check if a given object implements the GenerateInviteRequest interface.
 */
export function instanceOfGenerateInviteRequest(value: object): value is GenerateInviteRequest {
    return true;
}

export function GenerateInviteRequestFromJSON(json: any): GenerateInviteRequest {
    return GenerateInviteRequestFromJSONTyped(json, false);
}

export function GenerateInviteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateInviteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'condominiumId': json['condominiumId'] == null ? undefined : json['condominiumId'],
        'role': json['role'] == null ? undefined : ETipoUsuarioFromJSON(json['role']),
        'singleUse': json['singleUse'] == null ? undefined : json['singleUse'],
        'maxUses': json['maxUses'] == null ? undefined : json['maxUses'],
        'expiresInDays': json['expiresInDays'] == null ? undefined : json['expiresInDays'],
    };
}

export function GenerateInviteRequestToJSON(json: any): GenerateInviteRequest {
    return GenerateInviteRequestToJSONTyped(json, false);
}

export function GenerateInviteRequestToJSONTyped(value?: GenerateInviteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'condominiumId': value['condominiumId'],
        'role': ETipoUsuarioToJSON(value['role']),
        'singleUse': value['singleUse'],
        'maxUses': value['maxUses'],
        'expiresInDays': value['expiresInDays'],
    };
}

