/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateInviteResponse
 */
export interface GenerateInviteResponse {
    /**
     * 
     * @type {string}
     * @memberof GenerateInviteResponse
     */
    token?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof GenerateInviteResponse
     */
    expiresAt?: Date;
    /**
     * 
     * @type {string}
     * @memberof GenerateInviteResponse
     */
    role?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GenerateInviteResponse
     */
    condominiumId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof GenerateInviteResponse
     */
    singleUse?: boolean;
    /**
     * 
     * @type {number}
     * @memberof GenerateInviteResponse
     */
    maxUses?: number | null;
}

/**
 * Check if a given object implements the GenerateInviteResponse interface.
 */
export function instanceOfGenerateInviteResponse(value: object): value is GenerateInviteResponse {
    return true;
}

export function GenerateInviteResponseFromJSON(json: any): GenerateInviteResponse {
    return GenerateInviteResponseFromJSONTyped(json, false);
}

export function GenerateInviteResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateInviteResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'token': json['token'] == null ? undefined : json['token'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
        'role': json['role'] == null ? undefined : json['role'],
        'condominiumId': json['condominiumId'] == null ? undefined : json['condominiumId'],
        'singleUse': json['singleUse'] == null ? undefined : json['singleUse'],
        'maxUses': json['maxUses'] == null ? undefined : json['maxUses'],
    };
}

export function GenerateInviteResponseToJSON(json: any): GenerateInviteResponse {
    return GenerateInviteResponseToJSONTyped(json, false);
}

export function GenerateInviteResponseToJSONTyped(value?: GenerateInviteResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'token': value['token'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
        'role': value['role'],
        'condominiumId': value['condominiumId'],
        'singleUse': value['singleUse'],
        'maxUses': value['maxUses'],
    };
}

