/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetCepInput
 */
export interface GetCepInput {
    /**
     * 
     * @type {string}
     * @memberof GetCepInput
     */
    cep?: string | null;
}

/**
 * Check if a given object implements the GetCepInput interface.
 */
export function instanceOfGetCepInput(value: object): value is GetCepInput {
    return true;
}

export function GetCepInputFromJSON(json: any): GetCepInput {
    return GetCepInputFromJSONTyped(json, false);
}

export function GetCepInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetCepInput {
    if (json == null) {
        return json;
    }
    return {
        
        'cep': json['cep'] == null ? undefined : json['cep'],
    };
}

export function GetCepInputToJSON(json: any): GetCepInput {
    return GetCepInputToJSONTyped(json, false);
}

export function GetCepInputToJSONTyped(value?: GetCepInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'cep': value['cep'],
    };
}

