/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RegisterResponse
 */
export interface RegisterResponse {
    /**
     * 
     * @type {boolean}
     * @memberof RegisterResponse
     */
    sucesso?: boolean;
    /**
     * 
     * @type {string}
     * @memberof RegisterResponse
     */
    mensagem?: string | null;
}

/**
 * Check if a given object implements the RegisterResponse interface.
 */
export function instanceOfRegisterResponse(value: object): value is RegisterResponse {
    return true;
}

export function RegisterResponseFromJSON(json: any): RegisterResponse {
    return RegisterResponseFromJSONTyped(json, false);
}

export function RegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'sucesso': json['sucesso'] == null ? undefined : json['sucesso'],
        'mensagem': json['mensagem'] == null ? undefined : json['mensagem'],
    };
}

export function RegisterResponseToJSON(json: any): RegisterResponse {
    return RegisterResponseToJSONTyped(json, false);
}

export function RegisterResponseToJSONTyped(value?: RegisterResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sucesso': value['sucesso'],
        'mensagem': value['mensagem'],
    };
}

