/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EStatusReserva } from './EStatusReserva';
import {
    EStatusReservaFromJSON,
    EStatusReservaFromJSONTyped,
    EStatusReservaToJSON,
    EStatusReservaToJSONTyped,
} from './EStatusReserva';

/**
 * 
 * @export
 * @interface ReservationDto
 */
export interface ReservationDto {
    /**
     * 
     * @type {number}
     * @memberof ReservationDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ReservationDto
     */
    areaId?: number;
    /**
     * 
     * @type {number}
     * @memberof ReservationDto
     */
    condominiumId?: number;
    /**
     * 
     * @type {number}
     * @memberof ReservationDto
     */
    vinculoResidencialId?: number;
    /**
     * 
     * @type {string}
     * @memberof ReservationDto
     */
    purpose?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof ReservationDto
     */
    date?: Date;
    /**
     * 
     * @type {string}
     * @memberof ReservationDto
     */
    startTime?: string;
    /**
     * 
     * @type {string}
     * @memberof ReservationDto
     */
    endTime?: string;
    /**
     * 
     * @type {number}
     * @memberof ReservationDto
     */
    guests?: number;
    /**
     * 
     * @type {EStatusReserva}
     * @memberof ReservationDto
     */
    status?: EStatusReserva;
    /**
     * 
     * @type {string}
     * @memberof ReservationDto
     */
    notes?: string | null;
}



/**
 * Check if a given object implements the ReservationDto interface.
 */
export function instanceOfReservationDto(value: object): value is ReservationDto {
    return true;
}

export function ReservationDtoFromJSON(json: any): ReservationDto {
    return ReservationDtoFromJSONTyped(json, false);
}

export function ReservationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReservationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'areaId': json['areaId'] == null ? undefined : json['areaId'],
        'condominiumId': json['condominiumId'] == null ? undefined : json['condominiumId'],
        'vinculoResidencialId': json['vinculoResidencialId'] == null ? undefined : json['vinculoResidencialId'],
        'purpose': json['purpose'] == null ? undefined : json['purpose'],
        'date': json['date'] == null ? undefined : (new Date(json['date'])),
        'startTime': json['startTime'] == null ? undefined : json['startTime'],
        'endTime': json['endTime'] == null ? undefined : json['endTime'],
        'guests': json['guests'] == null ? undefined : json['guests'],
        'status': json['status'] == null ? undefined : EStatusReservaFromJSON(json['status']),
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function ReservationDtoToJSON(json: any): ReservationDto {
    return ReservationDtoToJSONTyped(json, false);
}

export function ReservationDtoToJSONTyped(value?: ReservationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'areaId': value['areaId'],
        'condominiumId': value['condominiumId'],
        'vinculoResidencialId': value['vinculoResidencialId'],
        'purpose': value['purpose'],
        'date': value['date'] == null ? value['date'] : value['date'].toISOString(),
        'startTime': value['startTime'],
        'endTime': value['endTime'],
        'guests': value['guests'],
        'status': EStatusReservaToJSON(value['status']),
        'notes': value['notes'],
    };
}

