/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ETipoOcupacao } from './ETipoOcupacao';
import {
    ETipoOcupacaoFromJSON,
    ETipoOcupacaoFromJSONTyped,
    ETipoOcupacaoToJSON,
    ETipoOcupacaoToJSONTyped,
} from './ETipoOcupacao';
import type { EStatusVinculoResidencial } from './EStatusVinculoResidencial';
import {
    EStatusVinculoResidencialFromJSON,
    EStatusVinculoResidencialFromJSONTyped,
    EStatusVinculoResidencialToJSON,
    EStatusVinculoResidencialToJSONTyped,
} from './EStatusVinculoResidencial';

/**
 * 
 * @export
 * @interface ResidentialLinkDto
 */
export interface ResidentialLinkDto {
    /**
     * 
     * @type {number}
     * @memberof ResidentialLinkDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof ResidentialLinkDto
     */
    usuarioId?: number;
    /**
     * 
     * @type {string}
     * @memberof ResidentialLinkDto
     */
    userName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ResidentialLinkDto
     */
    condominiumId?: number;
    /**
     * 
     * @type {string}
     * @memberof ResidentialLinkDto
     */
    condominiumName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ResidentialLinkDto
     */
    apartmentId?: number;
    /**
     * 
     * @type {string}
     * @memberof ResidentialLinkDto
     */
    apartmentNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ResidentialLinkDto
     */
    blockId?: number;
    /**
     * 
     * @type {string}
     * @memberof ResidentialLinkDto
     */
    blockName?: string | null;
    /**
     * 
     * @type {ETipoOcupacao}
     * @memberof ResidentialLinkDto
     */
    occupationType?: ETipoOcupacao;
    /**
     * 
     * @type {boolean}
     * @memberof ResidentialLinkDto
     */
    active?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof ResidentialLinkDto
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ResidentialLinkDto
     */
    endDate?: Date | null;
    /**
     * 
     * @type {EStatusVinculoResidencial}
     * @memberof ResidentialLinkDto
     */
    status?: EStatusVinculoResidencial;
}



/**
 * Check if a given object implements the ResidentialLinkDto interface.
 */
export function instanceOfResidentialLinkDto(value: object): value is ResidentialLinkDto {
    return true;
}

export function ResidentialLinkDtoFromJSON(json: any): ResidentialLinkDto {
    return ResidentialLinkDtoFromJSONTyped(json, false);
}

export function ResidentialLinkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResidentialLinkDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'usuarioId': json['usuarioId'] == null ? undefined : json['usuarioId'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'condominiumId': json['condominiumId'] == null ? undefined : json['condominiumId'],
        'condominiumName': json['condominiumName'] == null ? undefined : json['condominiumName'],
        'apartmentId': json['apartmentId'] == null ? undefined : json['apartmentId'],
        'apartmentNumber': json['apartmentNumber'] == null ? undefined : json['apartmentNumber'],
        'blockId': json['blockId'] == null ? undefined : json['blockId'],
        'blockName': json['blockName'] == null ? undefined : json['blockName'],
        'occupationType': json['occupationType'] == null ? undefined : ETipoOcupacaoFromJSON(json['occupationType']),
        'active': json['active'] == null ? undefined : json['active'],
        'startDate': json['startDate'] == null ? undefined : (new Date(json['startDate'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'status': json['status'] == null ? undefined : EStatusVinculoResidencialFromJSON(json['status']),
    };
}

export function ResidentialLinkDtoToJSON(json: any): ResidentialLinkDto {
    return ResidentialLinkDtoToJSONTyped(json, false);
}

export function ResidentialLinkDtoToJSONTyped(value?: ResidentialLinkDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'usuarioId': value['usuarioId'],
        'userName': value['userName'],
        'condominiumId': value['condominiumId'],
        'condominiumName': value['condominiumName'],
        'apartmentId': value['apartmentId'],
        'apartmentNumber': value['apartmentNumber'],
        'blockId': value['blockId'],
        'blockName': value['blockName'],
        'occupationType': ETipoOcupacaoToJSON(value['occupationType']),
        'active': value['active'],
        'startDate': value['startDate'] == null ? value['startDate'] : value['startDate'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'status': EStatusVinculoResidencialToJSON(value['status']),
    };
}

