/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReviewResidentialLinkRequest
 */
export interface ReviewResidentialLinkRequest {
    /**
     * 
     * @type {number}
     * @memberof ReviewResidentialLinkRequest
     */
    linkId?: number;
    /**
     * 
     * @type {boolean}
     * @memberof ReviewResidentialLinkRequest
     */
    aprovar?: boolean;
}

/**
 * Check if a given object implements the ReviewResidentialLinkRequest interface.
 */
export function instanceOfReviewResidentialLinkRequest(value: object): value is ReviewResidentialLinkRequest {
    return true;
}

export function ReviewResidentialLinkRequestFromJSON(json: any): ReviewResidentialLinkRequest {
    return ReviewResidentialLinkRequestFromJSONTyped(json, false);
}

export function ReviewResidentialLinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReviewResidentialLinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'linkId': json['linkId'] == null ? undefined : json['linkId'],
        'aprovar': json['aprovar'] == null ? undefined : json['aprovar'],
    };
}

export function ReviewResidentialLinkRequestToJSON(json: any): ReviewResidentialLinkRequest {
    return ReviewResidentialLinkRequestToJSONTyped(json, false);
}

export function ReviewResidentialLinkRequestToJSONTyped(value?: ReviewResidentialLinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'linkId': value['linkId'],
        'aprovar': value['aprovar'],
    };
}

