/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EStatusEncomenda } from './EStatusEncomenda';
import {
    EStatusEncomendaFromJSON,
    EStatusEncomendaFromJSONTyped,
    EStatusEncomendaToJSON,
    EStatusEncomendaToJSONTyped,
} from './EStatusEncomenda';

/**
 * 
 * @export
 * @interface UpdatePackageStatusInput
 */
export interface UpdatePackageStatusInput {
    /**
     * 
     * @type {number}
     * @memberof UpdatePackageStatusInput
     */
    packageId?: number;
    /**
     * 
     * @type {EStatusEncomenda}
     * @memberof UpdatePackageStatusInput
     */
    status?: EStatusEncomenda;
    /**
     * 
     * @type {string}
     * @memberof UpdatePackageStatusInput
     */
    pickupPersonName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UpdatePackageStatusInput
     */
    pickedUpAt?: Date | null;
}



/**
 * Check if a given object implements the UpdatePackageStatusInput interface.
 */
export function instanceOfUpdatePackageStatusInput(value: object): value is UpdatePackageStatusInput {
    return true;
}

export function UpdatePackageStatusInputFromJSON(json: any): UpdatePackageStatusInput {
    return UpdatePackageStatusInputFromJSONTyped(json, false);
}

export function UpdatePackageStatusInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdatePackageStatusInput {
    if (json == null) {
        return json;
    }
    return {
        
        'packageId': json['packageId'] == null ? undefined : json['packageId'],
        'status': json['status'] == null ? undefined : EStatusEncomendaFromJSON(json['status']),
        'pickupPersonName': json['pickupPersonName'] == null ? undefined : json['pickupPersonName'],
        'pickedUpAt': json['pickedUpAt'] == null ? undefined : (new Date(json['pickedUpAt'])),
    };
}

export function UpdatePackageStatusInputToJSON(json: any): UpdatePackageStatusInput {
    return UpdatePackageStatusInputToJSONTyped(json, false);
}

export function UpdatePackageStatusInputToJSONTyped(value?: UpdatePackageStatusInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'packageId': value['packageId'],
        'status': EStatusEncomendaToJSON(value['status']),
        'pickupPersonName': value['pickupPersonName'],
        'pickedUpAt': value['pickedUpAt'] == null ? value['pickedUpAt'] : value['pickedUpAt'].toISOString(),
    };
}

