/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpsertCommonAreaInput
 */
export interface UpsertCommonAreaInput {
    /**
     * 
     * @type {number}
     * @memberof UpsertCommonAreaInput
     */
    id?: number | null;
    /**
     * 
     * @type {number}
     * @memberof UpsertCommonAreaInput
     */
    condominiumId?: number;
    /**
     * 
     * @type {string}
     * @memberof UpsertCommonAreaInput
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpsertCommonAreaInput
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UpsertCommonAreaInput
     */
    type?: string | null;
    /**
     * 
     * @type {number}
     * @memberof UpsertCommonAreaInput
     */
    capacity?: number;
    /**
     * 
     * @type {string}
     * @memberof UpsertCommonAreaInput
     */
    openingTime?: string;
    /**
     * 
     * @type {string}
     * @memberof UpsertCommonAreaInput
     */
    closingTime?: string;
    /**
     * 
     * @type {number}
     * @memberof UpsertCommonAreaInput
     */
    maxDuration?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UpsertCommonAreaInput
     */
    available?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UpsertCommonAreaInput
     */
    requiresApproval?: boolean;
    /**
     * 
     * @type {number}
     * @memberof UpsertCommonAreaInput
     */
    availableDays?: number;
    /**
     * 
     * @type {string}
     * @memberof UpsertCommonAreaInput
     */
    notes?: string | null;
}

/**
 * Check if a given object implements the UpsertCommonAreaInput interface.
 */
export function instanceOfUpsertCommonAreaInput(value: object): value is UpsertCommonAreaInput {
    return true;
}

export function UpsertCommonAreaInputFromJSON(json: any): UpsertCommonAreaInput {
    return UpsertCommonAreaInputFromJSONTyped(json, false);
}

export function UpsertCommonAreaInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpsertCommonAreaInput {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'condominiumId': json['condominiumId'] == null ? undefined : json['condominiumId'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'type': json['type'] == null ? undefined : json['type'],
        'capacity': json['capacity'] == null ? undefined : json['capacity'],
        'openingTime': json['openingTime'] == null ? undefined : json['openingTime'],
        'closingTime': json['closingTime'] == null ? undefined : json['closingTime'],
        'maxDuration': json['maxDuration'] == null ? undefined : json['maxDuration'],
        'available': json['available'] == null ? undefined : json['available'],
        'requiresApproval': json['requiresApproval'] == null ? undefined : json['requiresApproval'],
        'availableDays': json['availableDays'] == null ? undefined : json['availableDays'],
        'notes': json['notes'] == null ? undefined : json['notes'],
    };
}

export function UpsertCommonAreaInputToJSON(json: any): UpsertCommonAreaInput {
    return UpsertCommonAreaInputToJSONTyped(json, false);
}

export function UpsertCommonAreaInputToJSONTyped(value?: UpsertCommonAreaInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'condominiumId': value['condominiumId'],
        'name': value['name'],
        'description': value['description'],
        'type': value['type'],
        'capacity': value['capacity'],
        'openingTime': value['openingTime'],
        'closingTime': value['closingTime'],
        'maxDuration': value['maxDuration'],
        'available': value['available'],
        'requiresApproval': value['requiresApproval'],
        'availableDays': value['availableDays'],
        'notes': value['notes'],
    };
}

