/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDto } from './UserDto';
import {
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
    UserDtoToJSONTyped,
} from './UserDto';
import type { CondominiumDto } from './CondominiumDto';
import {
    CondominiumDtoFromJSON,
    CondominiumDtoFromJSONTyped,
    CondominiumDtoToJSON,
    CondominiumDtoToJSONTyped,
} from './CondominiumDto';
import type { ETipoUsuario } from './ETipoUsuario';
import {
    ETipoUsuarioFromJSON,
    ETipoUsuarioFromJSONTyped,
    ETipoUsuarioToJSON,
    ETipoUsuarioToJSONTyped,
} from './ETipoUsuario';

/**
 * 
 * @export
 * @interface UserCondominiumDto
 */
export interface UserCondominiumDto {
    /**
     * 
     * @type {number}
     * @memberof UserCondominiumDto
     */
    userId?: number;
    /**
     * 
     * @type {number}
     * @memberof UserCondominiumDto
     */
    condominiumId?: number;
    /**
     * 
     * @type {ETipoUsuario}
     * @memberof UserCondominiumDto
     */
    userType?: ETipoUsuario;
    /**
     * 
     * @type {boolean}
     * @memberof UserCondominiumDto
     */
    active?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UserCondominiumDto
     */
    creationTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof UserCondominiumDto
     */
    endDate?: Date | null;
    /**
     * 
     * @type {UserDto}
     * @memberof UserCondominiumDto
     */
    user?: UserDto;
    /**
     * 
     * @type {CondominiumDto}
     * @memberof UserCondominiumDto
     */
    condominium?: CondominiumDto;
}



/**
 * Check if a given object implements the UserCondominiumDto interface.
 */
export function instanceOfUserCondominiumDto(value: object): value is UserCondominiumDto {
    return true;
}

export function UserCondominiumDtoFromJSON(json: any): UserCondominiumDto {
    return UserCondominiumDtoFromJSONTyped(json, false);
}

export function UserCondominiumDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCondominiumDto {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'condominiumId': json['condominiumId'] == null ? undefined : json['condominiumId'],
        'userType': json['userType'] == null ? undefined : ETipoUsuarioFromJSON(json['userType']),
        'active': json['active'] == null ? undefined : json['active'],
        'creationTime': json['creationTime'] == null ? undefined : (new Date(json['creationTime'])),
        'endDate': json['endDate'] == null ? undefined : (new Date(json['endDate'])),
        'user': json['user'] == null ? undefined : UserDtoFromJSON(json['user']),
        'condominium': json['condominium'] == null ? undefined : CondominiumDtoFromJSON(json['condominium']),
    };
}

export function UserCondominiumDtoToJSON(json: any): UserCondominiumDto {
    return UserCondominiumDtoToJSONTyped(json, false);
}

export function UserCondominiumDtoToJSONTyped(value?: UserCondominiumDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'condominiumId': value['condominiumId'],
        'userType': ETipoUsuarioToJSON(value['userType']),
        'active': value['active'],
        'creationTime': value['creationTime'] == null ? value['creationTime'] : value['creationTime'].toISOString(),
        'endDate': value['endDate'] == null ? value['endDate'] : value['endDate'].toISOString(),
        'user': UserDtoToJSON(value['user']),
        'condominium': CondominiumDtoToJSON(value['condominium']),
    };
}

