/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CondominioDto } from './CondominioDto';
import {
    CondominioDtoFromJSON,
    CondominioDtoFromJSONTyped,
    CondominioDtoToJSON,
    CondominioDtoToJSONTyped,
} from './CondominioDto';
import type { UsuarioDto } from './UsuarioDto';
import {
    UsuarioDtoFromJSON,
    UsuarioDtoFromJSONTyped,
    UsuarioDtoToJSON,
    UsuarioDtoToJSONTyped,
} from './UsuarioDto';
import type { ETipoUsuario } from './ETipoUsuario';
import {
    ETipoUsuarioFromJSON,
    ETipoUsuarioFromJSONTyped,
    ETipoUsuarioToJSON,
    ETipoUsuarioToJSONTyped,
} from './ETipoUsuario';

/**
 * 
 * @export
 * @interface UsuarioCondominioDto
 */
export interface UsuarioCondominioDto {
    /**
     * 
     * @type {number}
     * @memberof UsuarioCondominioDto
     */
    usuarioId?: number;
    /**
     * 
     * @type {number}
     * @memberof UsuarioCondominioDto
     */
    condominioId?: number;
    /**
     * 
     * @type {ETipoUsuario}
     * @memberof UsuarioCondominioDto
     */
    tipoUsuario?: ETipoUsuario;
    /**
     * 
     * @type {boolean}
     * @memberof UsuarioCondominioDto
     */
    ativo?: boolean;
    /**
     * 
     * @type {Date}
     * @memberof UsuarioCondominioDto
     */
    dataInicio?: Date;
    /**
     * 
     * @type {UsuarioDto}
     * @memberof UsuarioCondominioDto
     */
    usuario?: UsuarioDto;
    /**
     * 
     * @type {CondominioDto}
     * @memberof UsuarioCondominioDto
     */
    condominio?: CondominioDto;
}



/**
 * Check if a given object implements the UsuarioCondominioDto interface.
 */
export function instanceOfUsuarioCondominioDto(value: object): value is UsuarioCondominioDto {
    return true;
}

export function UsuarioCondominioDtoFromJSON(json: any): UsuarioCondominioDto {
    return UsuarioCondominioDtoFromJSONTyped(json, false);
}

export function UsuarioCondominioDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsuarioCondominioDto {
    if (json == null) {
        return json;
    }
    return {
        
        'usuarioId': json['usuarioId'] == null ? undefined : json['usuarioId'],
        'condominioId': json['condominioId'] == null ? undefined : json['condominioId'],
        'tipoUsuario': json['tipoUsuario'] == null ? undefined : ETipoUsuarioFromJSON(json['tipoUsuario']),
        'ativo': json['ativo'] == null ? undefined : json['ativo'],
        'dataInicio': json['dataInicio'] == null ? undefined : (new Date(json['dataInicio'])),
        'usuario': json['usuario'] == null ? undefined : UsuarioDtoFromJSON(json['usuario']),
        'condominio': json['condominio'] == null ? undefined : CondominioDtoFromJSON(json['condominio']),
    };
}

export function UsuarioCondominioDtoToJSON(json: any): UsuarioCondominioDto {
    return UsuarioCondominioDtoToJSONTyped(json, false);
}

export function UsuarioCondominioDtoToJSONTyped(value?: UsuarioCondominioDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usuarioId': value['usuarioId'],
        'condominioId': value['condominioId'],
        'tipoUsuario': ETipoUsuarioToJSON(value['tipoUsuario']),
        'ativo': value['ativo'],
        'dataInicio': value['dataInicio'] == null ? value['dataInicio'] : value['dataInicio'].toISOString(),
        'usuario': UsuarioDtoToJSON(value['usuario']),
        'condominio': CondominioDtoToJSON(value['condominio']),
    };
}

