/* tslint:disable */
/* eslint-disable */
/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UsuarioDto
 */
export interface UsuarioDto {
    /**
     * 
     * @type {number}
     * @memberof UsuarioDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UsuarioDto
     */
    nome?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UsuarioDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UsuarioDto
     */
    telefone?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UsuarioDto
     */
    cpf?: string | null;
}

/**
 * Check if a given object implements the UsuarioDto interface.
 */
export function instanceOfUsuarioDto(value: object): value is UsuarioDto {
    return true;
}

export function UsuarioDtoFromJSON(json: any): UsuarioDto {
    return UsuarioDtoFromJSONTyped(json, false);
}

export function UsuarioDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsuarioDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'nome': json['nome'] == null ? undefined : json['nome'],
        'email': json['email'] == null ? undefined : json['email'],
        'telefone': json['telefone'] == null ? undefined : json['telefone'],
        'cpf': json['cpf'] == null ? undefined : json['cpf'],
    };
}

export function UsuarioDtoToJSON(json: any): UsuarioDto {
    return UsuarioDtoToJSONTyped(json, false);
}

export function UsuarioDtoToJSONTyped(value?: UsuarioDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'nome': value['nome'],
        'email': value['email'],
        'telefone': value['telefone'],
        'cpf': value['cpf'],
    };
}

